/**
 * @packageDocumentation
 * Sidebars for the classic docs plugin (developer docs).
 */
import { createRequire } from "node:module";

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const require = createRequire(import.meta.url);

const typedocSidebar: unknown = require("./site-docs/developer/api/typedoc-sidebar.cjs");

type UnknownRecord = Record<string, unknown>;

/**
 * @param value - Unknown runtime value.
 *
 * @returns Whether the value is a non-array object record.
 */
const isRecord = (value: unknown): value is UnknownRecord =>
    typeof value === "object" && value !== null && !Array.isArray(value);

/**
 * Normalize generated TypeDoc ids from "../site-docs/developer/api/..." to
 * "developer/api/...".
 *
 * @param value - Raw generated id.
 *
 * @returns Normalized Docusaurus docs id.
 */
const normalizeTypedocId = (value: string): string =>
    value
        .replace(/^\.\.\/site-docs\//u, "")
        .replace(
            /\/stylelintconfig-references(\/|$)/u,
            "/stylelint2-config-references$1"
        );

/**
 * Recursively normalize generated TypeDoc sidebar items so they can be mounted
 * in the classic docs sidebar.
 *
 * @param value - Raw generated sidebar item.
 *
 * @returns Normalized sidebar item.
 */
const normalizeTypedocSidebarItem = (value: unknown): unknown => {
    if (Array.isArray(value)) {
        return value.map((item) => normalizeTypedocSidebarItem(item));
    }

    if (!isRecord(value)) {
        return value;
    }

    const normalizedEntries = Object.entries(value).map(([key, entryValue]) => {
        if (key === "id" && typeof entryValue === "string") {
            return [key, normalizeTypedocId(entryValue)] as const;
        }

        return [key, normalizeTypedocSidebarItem(entryValue)] as const;
    });
    const normalized = Object.fromEntries(normalizedEntries) as UnknownRecord;

    if (
        normalized["type"] === "category" &&
        typeof normalized["label"] === "string"
    ) {
        const normalizedLabel = normalized["label"].toLowerCase();

        if (normalizedLabel === "plugin") {
            normalized["className"] = "sb-cat-api-runtime";
            normalized["collapsed"] = false;
            normalized["collapsible"] = true;
            normalized["label"] = "📦 Plugin API";
        }

        if (normalizedLabel === "internal") {
            normalized["className"] = "sb-cat-api-internal";
            normalized["collapsed"] = false;
            normalized["collapsible"] = true;
            normalized["label"] = "🧬 Internal API";
        }
    }

    return normalized;
};

const typedocSidebarItems = Array.isArray(typedocSidebar)
    ? typedocSidebar.map((item) => normalizeTypedocSidebarItem(item))
    : [];

const sidebars = {
    docs: [
        {
            className: "sb-cat-developer",
            collapsed: false,
            collapsible: true,
            label: "🧩 Developer",
            type: "category",
            items: [
                {
                    className: "sb-cat-api-overview",
                    id: "developer/api/index",
                    label: "📘 API Overview",
                    type: "doc",
                },
                {
                    className: "sb-cat-dev-links",
                    collapsed: false,
                    collapsible: true,
                    label: "🧭 Developer Guides",
                    type: "category",
                    items: [
                        {
                            dirName: "developer/guides",
                            type: "autogenerated",
                        },
                    ],
                },
                {
                    className: "sb-cat-developer-adrs",
                    collapsed: false,
                    collapsible: true,
                    label: "🏛️ ADRs",
                    type: "category",
                    items: [
                        {
                            dirName: "developer/adr",
                            type: "autogenerated",
                        },
                    ],
                },
                {
                    className: "sb-cat-api-runtime",
                    collapsed: false,
                    collapsible: true,
                    label: "📦 TypeDoc API Reference",
                    type: "category",
                    items: typedocSidebarItems as SidebarsConfig["docs"],
                },
            ],
        },
    ],
} satisfies SidebarsConfig;

export default sidebars;
