import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * @packageDocumentation
 * Sidebars for the classic docs plugin (developer docs).
 */
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

const typedocSidebar: unknown = require("./site-docs/developer/api/typedoc-sidebar.cjs");

type SidebarConfig = SidebarsConfig[string];
type UnknownRecord = Record<string, unknown>;

/**
 * @param value - Unknown runtime value.
 *
 * @returns Whether the value is a non-array object record.
 */
const isRecord = (value: unknown): value is UnknownRecord =>
    typeof value === "object" && value !== null && !Array.isArray(value);

/**
 * Validate the generated TypeDoc sidebar subset consumed by this site.
 *
 * @param value - Potential generated sidebar item.
 *
 * @returns Whether the value is a supported Docusaurus sidebar item.
 */
const isGeneratedSidebarItem = (value: unknown): boolean => {
    if (typeof value === "string") {
        return true;
    }

    if (!isRecord(value) || typeof value["type"] !== "string") {
        return false;
    }

    switch (value["type"]) {
        case "autogenerated": {
            return typeof value["dirName"] === "string";
        }
        case "category": {
            return (
                typeof value["label"] === "string" &&
                Array.isArray(value["items"]) &&
                value["items"].every((item) => isGeneratedSidebarItem(item))
            );
        }
        case "doc":
        case "ref": {
            return typeof value["id"] === "string";
        }
        case "html": {
            return typeof value["value"] === "string";
        }
        case "link": {
            return (
                typeof value["href"] === "string" &&
                typeof value["label"] === "string"
            );
        }
        default: {
            return false;
        }
    }
};

/** Validate the generated top-level sidebar before using it as config. */
const isSidebarConfig = (value: unknown): value is SidebarConfig =>
    Array.isArray(value) && value.every((item) => isGeneratedSidebarItem(item));

/**
 * Normalize generated TypeDoc ids from "../site-docs/developer/api/..." to
 * "developer/api/...".
 *
 * @param value - Raw generated id.
 *
 * @returns Normalized Docusaurus docs id.
 */
const normalizeTypedocId = (value: string): string =>
    value
        .replace(/^\.\.\/site-docs\//u, "")
        .replace(
            /\/stylelintconfig-references(?=\/|$)/u,
            "/stylelint2-config-references"
        );

/**
 * Recursively normalize generated TypeDoc sidebar items so they can be mounted
 * in the classic docs sidebar.
 *
 * @param value - Raw generated sidebar item.
 *
 * @returns Normalized sidebar item.
 */
const normalizeTypedocSidebarItem = (value: unknown): unknown => {
    if (Array.isArray(value)) {
        return value.map((item) => normalizeTypedocSidebarItem(item));
    }

    if (!isRecord(value)) {
        return value;
    }

    const normalizedEntries = Object.entries(value).map(([key, entryValue]) => {
        if (key === "id" && typeof entryValue === "string") {
            return [key, normalizeTypedocId(entryValue)] as const;
        }

        return [key, normalizeTypedocSidebarItem(entryValue)] as const;
    });
    const normalized = Object.fromEntries(normalizedEntries);

    if (
        normalized["type"] === "category" &&
        typeof normalized["label"] === "string"
    ) {
        const normalizedLabel = normalized["label"].toLowerCase();

        if (normalizedLabel === "plugin") {
            normalized["className"] = "sb-cat-api-runtime";
            normalized["collapsed"] = false;
            normalized["collapsible"] = true;
            normalized["label"] = "📦 Plugin API";
        }

        if (normalizedLabel === "internal") {
            normalized["className"] = "sb-cat-api-internal";
            normalized["collapsed"] = false;
            normalized["collapsible"] = true;
            normalized["label"] = "🧬 Internal API";
        }
    }

    return normalized;
};

const normalizedTypedocSidebar = normalizeTypedocSidebarItem(typedocSidebar);

if (!isSidebarConfig(normalizedTypedocSidebar)) {
    throw new TypeError(
        "The generated TypeDoc sidebar does not match the supported Docusaurus sidebar schema."
    );
}

const typedocSidebarItems = normalizedTypedocSidebar;

const sidebars = {
    docs: [
        {
            className: "sb-cat-developer",
            collapsed: false,
            collapsible: true,
            items: [
                {
                    className: "sb-cat-api-overview",
                    id: "developer/api/index",
                    label: "📘 API Overview",
                    type: "doc",
                },
                {
                    className: "sb-cat-dev-links",
                    collapsed: false,
                    collapsible: true,
                    items: [
                        {
                            dirName: "developer/guides",
                            type: "autogenerated",
                        },
                    ],
                    label: "🧭 Developer Guides",
                    type: "category",
                },
                {
                    className: "sb-cat-developer-adrs",
                    collapsed: false,
                    collapsible: true,
                    items: [
                        {
                            dirName: "developer/adr",
                            type: "autogenerated",
                        },
                    ],
                    label: "🏛️ ADRs",
                    type: "category",
                },
                {
                    className: "sb-cat-api-runtime",
                    collapsed: false,
                    collapsible: true,
                    items: typedocSidebarItems,
                    label: "📦 TypeDoc API Reference",
                    type: "category",
                },
            ],
            label: "🧩 Developer",
            type: "category",
        },
    ],
} satisfies SidebarsConfig;

export default sidebars;
